In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("ai_job_dataset.csv")

In [3]:
df.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,18-10-24,07-11-24,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,20-11-24,11-01-25,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,18-03-25,07-04-25,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,23-12-24,24-02-25,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,15-04-25,23-06-25,1989,6.6,Advanced Robotics

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  15000 non-null  object
 1   job_title               15000 non-null  object
 2   salary_usd              15000 non-null  int64
 3   salary_currency         15000 non-null  object
 4   experience_level        15000 non-null  object
 5   employment_type         15000 non-null  object
 6   company_location        15000 non-null  object
 7   company_size            15000 non-null  object
 8   employee_residence      15000 non-null  object
 9   remote_ratio            15000 non-null  int64
 10  required_skills         15000 non-null  object
 11  education_required      15000 non-null  object
 12  years_experience        15000 non-null  int64
 13  industry                15000 non-null  object
 14  posting_date            15000 non-null  object
 15  application_deadline    15000 non-null  object
 16  job_description_length  15000 non-null  int64
 17  benefits_score          15000 non-null  float64
 18  company_name            15000 non-null  object
dtypes: float64(1), int64(4), object(14)
memory usage: 2.2+ MB

In [5]:
df.describe()

,salary_usd,remote_ratio,years_experience,job_description_length,benefits_score
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,115348.965133,49.483333,6.253200,1503.314733,7.504273
std,60260.940438,40.812712,5.545768,576.127083,1.450870
min,32519.000000,0.000000,0.000000,500.000000,5.000000
25%,70179.750000,0.000000,2.000000,1003.750000,6.200000
50%,99705.000000,50.000000,5.000000,1512.000000,7.500000
75%,146408.500000,100.000000,10.000000,2000.000000,8.800000
max,399095.000000,100.000000,19.000000,2499.000000,10.000000

In [6]:
df.duplicated().any()

np.False_

In [7]:
df["experience_level"].unique()

array(['SE', 'EN', 'MI', 'EX'], dtype=object)

In [8]:
df["experience_level"]=df["experience_level"].replace({'SE':"Senior",
                                'EN':"Entry",
                                'MI':"Mid",
                                'EX':"Executive"
                                })

In [9]:
df["employment_type"].unique()

array(['CT', 'FL', 'PT', 'FT'], dtype=object)

In [10]:
df["employment_type"]=df["employment_type"].replace({"CT":"Contract",
                               "FL":"Freelance",
                               "PT":"Part-time",
                               "FT":"Full-time"
                               })

In [11]:
df["company_size"].unique()

array(['M', 'L', 'S'], dtype=object)

In [12]:
df["company_size"]=df["company_size"].replace({"M":"Medium",
                            "L":"Large",
                            "S":"Small"})

In [13]:
df = df.rename(columns={"remote_ratio": "work_mode",
                        "salary_usd":"salary"
                        })

In [14]:
df["work_mode"].unique()

array([ 50, 100,   0])

In [15]:
df["work_mode"]=df["work_mode"].replace({0:"On-Site",
                        50:"Hybrid",
                         100:"Remote"})

In [16]:
df.head(1)

,job_id,job_title,salary,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,work_mode,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,Senior,Contract,China,Medium,China,Hybrid,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,18-10-24,07-11-24,1076,5.9,Smart Analytics

In [17]:
df["required_skills"].head()

0           Tableau, PyTorch, Kubernetes, Linux, NLP
1    Deep Learning, AWS, Mathematics, Python, Docker
2       Kubernetes, Deep Learning, Java, Hadoop, NLP
3                          Scala, SQL, Linux, Python
4                       MLOps, Java, Tableau, Python
Name: required_skills, dtype: object

In [18]:
# df[["skill_1", "skill_2","skill_3","skill_4","skill_5"]] = df["required_skills"].str.split(",",expand=True)

In [19]:
df["required_skills"] = df["required_skills"].str.split(",")

In [20]:
df=df.explode("required_skills")

In [21]:
df["required_skills"] = df["required_skills"].str.strip()

In [22]:
df = df.dropna(subset=["required_skills"])

In [23]:
skill_count = df["required_skills"].value_counts().reset_index()
skill_count.columns = ["skill", "frequency"]
print(skill_count.head())

        skill  frequency
0      Python       4450
1         SQL       3407
2  TensorFlow       3022
3  Kubernetes       3009
4       Scala       2794

In [24]:
df.columns

Index(['job_id', 'job_title', 'salary', 'salary_currency', 'experience_level',
       'employment_type', 'company_location', 'company_size',
       'employee_residence', 'work_mode', 'required_skills',
       'education_required', 'years_experience', 'industry', 'posting_date',
       'application_deadline', 'job_description_length', 'benefits_score',
       'company_name'],
      dtype='object')

In [25]:
df=df.drop(['salary_currency','years_experience', 'industry', 'posting_date',
       'application_deadline', 'job_description_length', 'benefits_score'], axis=1)

In [26]:
df.head()

,job_id,job_title,salary,experience_level,employment_type,company_location,company_size,employee_residence,work_mode,required_skills,education_required,company_name
0,AI00001,AI Research Scientist,90376,Senior,Contract,China,Medium,China,Hybrid,Tableau,Bachelor,Smart Analytics
0,AI00001,AI Research Scientist,90376,Senior,Contract,China,Medium,China,Hybrid,PyTorch,Bachelor,Smart Analytics
0,AI00001,AI Research Scientist,90376,Senior,Contract,China,Medium,China,Hybrid,Kubernetes,Bachelor,Smart Analytics
0,AI00001,AI Research Scientist,90376,Senior,Contract,China,Medium,China,Hybrid,Linux,Bachelor,Smart Analytics
0,AI00001,AI Research Scientist,90376,Senior,Contract,China,Medium,China,Hybrid,NLP,Bachelor,Smart Analytics

### Data import in MY SQL

In [ ]:
# first install IN TERMINAL 
# --------- pip install pymysql sqlalchemy -------------

In [28]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# MySQL Connection
username = "root"
password = quote_plus("7004217083")
host = "127.0.0.1"
port = "3306"
database = "ai_job_dataset_db"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = "ai_job"  # use lowercase for safety

# Write DataFrame
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
sample_df = pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5", engine)
print(sample_df)

    job_id              job_title  salary experience_level employment_type  \
0  AI00001  AI Research Scientist   90376           Senior        Contract
1  AI00001  AI Research Scientist   90376           Senior        Contract
2  AI00001  AI Research Scientist   90376           Senior        Contract
3  AI00001  AI Research Scientist   90376           Senior        Contract
4  AI00001  AI Research Scientist   90376           Senior        Contract

  company_location company_size employee_residence work_mode required_skills  \
0            China       Medium              China    Hybrid         Tableau
1            China       Medium              China    Hybrid         PyTorch
2            China       Medium              China    Hybrid      Kubernetes
3            China       Medium              China    Hybrid           Linux
4            China       Medium              China    Hybrid             NLP

  education_required     company_name
0           Bachelor  Smart Analytics
1           Bachelor  Smart Analytics
2           Bachelor  Smart Analytics
3           Bachelor  Smart Analytics
4           Bachelor  Smart Analytics

In [29]:
df.to_excel("clean.xlsx")